Support custom character icons / edition logos again with opt-in
bra1n/townsquare pull request #113
Opened 2021-02-04 20:57 UTC by bra1n

I've added support for sending custom edition characters through the live session again, as well as showing custom edition logos for players, after they opt in through the session menu.
This closes #74

2021-02-04 21:01 UTC, bra1n commented
@davotronic5000 would you like to review this PR before I merge it?

2021-02-05 21:17 UTC, bra1n commented
Sorry for the messy commit history. 😑

2021-02-10 22:05 UTC, davotronic5000 requested changes
Code looks great, only issus I have found is by deafult now the Story teller cannot see the custom images from a script they have uploaded, unless they have the image optin already saved from a player session.

2021-02-11 12:47 UTC, bra1n commented on src/components/Player.vue
> +              reminder.image && grimoire.isImageOptIn
Ooh, really good catch! Thanks, I totally missed that after enabling it for the host. I'll show the image opt-in in the Grimoire tab now, whether online or offline. (I've just realized that you don't even need to be in a live session to load homebrew scripts with custom images)

2021-02-11 19:33 UTC, merged