Fearmonger
bra1n/townsquare pull request #216
Opened 2021-09-09 23:09 UTC by eddgabriel

2021-09-10 08:14 UTC, bra1n requested changes
The icon image is awfully big - would you mind reducing it in size, please?

2021-09-11 14:41 UTC, eddgabriel commented
Should be good to go once checks have re-completed @bra1n

2021-09-11 15:54 UTC, bra1n approved these changes

2021-09-11 15:54 UTC, bra1n commented
Perfect, thanks!

2021-09-11 15:54 UTC, merged