Add V hotkey for voting history
bra1n/townsquare pull request #80
Opened 2021-01-04 15:54 UTC by lilserf

In the games my group has played recently, I've needed to refer to the nomination/vote history over and over, and I wished for a quick hotkey to toggle that window.

2021-01-04 19:34 UTC, bra1n requested changes
Don't forget to lint your changes. ;-)

2021-01-04 19:34 UTC, bra1n commented on src/App.vue
> +          this.$store.commit("toggleModal", "voteHistory");
The voteHistory modal should only open when there is an actual voteHistory to show:
```suggestion
          if (this.session.voteHistory.length) {
            this.$store.commit("toggleModal", "voteHistory");
          }
```

2021-01-04 19:34 UTC, bra1n commented on src/components/Menu.vue
> +            Nomination history<em>[V]</em>
```suggestion
            Nomination history<em>[V]</em>
```

2021-01-04 20:39 UTC, lilserf commented
I’m not sure if I correctly resolved the suggestions; I’m rusty on GitHub details and did it from my phone

2021-01-05 19:21 UTC, bra1n commented
> I’m not sure if I correctly resolved the suggestions; I’m rusty on GitHub details and did it from my phone.
> It's still showing "Changes requested" below.

Yeah, approval doesn't happen automatically on Github. :-)

2021-01-05 19:23 UTC, bra1n approved these changes
Looks good to me now. 👍  Thanks @lilserf for the PR!

2021-01-05 19:23 UTC, merged